from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class ChatMessageResponse(BaseModel):
    response: str = Field(..., description="Response content text generated by Azure AI Foundry.")
    session_id: Optional[str] = Field(None, description="Active conversation tracking session reference.")
    citations: List[str] = Field(default_factory=list, description="Extracted references or sources.")


class ImageChatResponse(BaseModel):
    response: str = Field(..., description="Vision analysis content text generated by Azure AI Foundry.")
    citations: List[str] = Field(default_factory=list, description="Extracted citations or bibliography elements.")


class LocationChatResponse(BaseModel):
    response: str = Field(..., description="AI description of coordinates, including transit routes or dining recommendations.")
    citations: List[str] = Field(default_factory=list, description="Relevant citations.")


class TravelPlanResponse(BaseModel):
    itinerary: str = Field(..., description="Generated daily travel itinerary markdown.")
    food_recommendations: str = Field(..., description="Dietary preference aligned dining guide recommendations.")
    transportation_recommendations: str = Field(..., description="Airport transit, rail or walking parameters.")
    travel_tips: str = Field(..., description="Health, safety or packing tips.")
    citations: List[str] = Field(default_factory=list, description="Relevant sources used to compile dynamic itinerary guides.")


class ExpenseResponse(BaseModel):
    id: int = Field(..., description="Database identifier key.")
    vendor: str = Field(..., description="The supplier or merchant name.")
    amount: float = Field(..., description="Cost amount.")
    currency: str = Field(..., description="Currency description.")
    category: str = Field(..., description="Category allocation for ledger processing.")
    type: str = Field(..., description="Division between Business and Personal.")
    date: str = Field(..., description="Standard YYYY-MM-DD date representation.")
    description: Optional[str] = Field(None, description="Detailed explanatory comments.")
    status: str = Field(..., description="Reimbursement validation status.")


class ExpenseSummaryResponse(BaseModel):
    total_business: float = Field(..., description="Sum total of all active business/reimbursable expenses, calculated in Base currency.")
    total_personal: float = Field(..., description="Sum total of all active individual/personal out-of-pocket costs.")
    grand_total: float = Field(..., description="Gross aggregate ledger amount.")
    by_category: Dict[str, float] = Field(default_factory=dict, description="Ledger amounts subtotaled by distinct categories.")
    count_reimbursable: int = Field(..., description="Total count of active reimbursable business expenses.")
